USE master
GO
 
CREATE DATABASE DBREVISAO
GO
 
USE DBREVISAO
GO
 
CREATE TABLE CLIENTEA(
Id INT IDENTITY,
Nome NVARCHAR(100) NOT NULL,
Usuario NVARCHAR(50) NOT NULL,
Senha NVARCHAR(MAX) NOT NULL
CONSTRAINT PKCLIENTEAID PRIMARY KEY(Id)
)
GO
CREATE TABLE CLIENTEB(
Id INT,
Nome NVARCHAR(100) NOT NULL,
Usuario NVARCHAR(50) NOT NULL,
Senha NVARCHAR(MAX) NOT NULL
CONSTRAINT PKCLIENTEBID PRIMARY KEY(Id)
)
GO
 
 
INSERT INTO CLIENTEA VALUES('CASSIO','CRSP','EUAMOMINHAMAE')
INSERT INTO CLIENTEB VALUES((SELECT MAX(Id) + 1 FROM CLIENTEB),'CASSIO','CRSP','EUAMOMINHAMAE')
 
SELECT * FROM CLIENTEA 
SELECT * FROM CLIENTEB
 
SELECT MAX(Id) + 1 FROM CLIENTEB